colors:
  primary:
    background: "#282828"
    foreground: "#ebdbb2"
  cursor:
    text: "#ffffff"
    cursor: "#ebdbb2"
  selection:
    text: "#ebdbb2"
    background: "#665c54"
  normal:
    black: "#282828"
    red: "#cc241d"
    green: "#98971a"
    yellow: "#d79921"
    blue: "#458588"
    magenta: "#b16286"
    cyan: "#689d6a"
    white: "#ebdbb2"
  bright:
    black: "#928374"
    red: "#fb4934"
    green: "#b8bb26"
    yellow: "#fabd2f"
    blue: "#83a598"
    magenta: "#d3869b"
    cyan: "#8ec07c"
    white: "#ebdbb2"

window:
    padding:
       x: 20
       y: 20

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Bold
  bold:
    family: JetBrainsMono Nerd Font
    style: Extra Bold
  italic:
    family: JetBrainsMono Nerd Font
    style: Italic
  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Extra Bold
  size: 9
  offset:
    y: 0
  glyph_offset:
    y: 0
