#! /bin/sh
#     __
#    / /_  _________ _      ______ ___
#   / __ \/ ___/ __ \ | /| / / __ `__ \
#  / /_/ (__  ) /_/ / |/ |/ / / / / / /
# /_.___/____/ .___/|__/|__/_/ /_/ /_/
#           /_/
# Dotfiles - Hayafumi

# Launch Hotkeys
pgrep -x sxhkd > /dev/null || sxhkd &

# Workspaces
bspc monitor HDMI2 -d 1 2 3 4 5
bspc monitor VGA1 -d 1 2 3 4 5

# BSPWM Settings
bspc config border_width 2
bspc config window_gap 10
bspc config focus_follows_pointer true

bspc config split_ratio          0.0
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color \#5B514A
bspc config focused_border_color \#CFBC99
bspc config presel_feedback_color \#5B514A

# Xset
xsetroot -cursor_name left_ptr &

# Autostart
picom & # Launch Compositor
dunst & # Notifications
nitrogen --restore & # Set Wallpaper
~/.config/polybar/launch.sh # Status Bar
